'''
XPATH AND XPATH OPTIONS
-----------------------
Xpath is an XML Path
It is used to find elements on the weebpage
It is used for dynamically changing elements on the webpage e.g prices on a web page because it changes
Xpath is also an address or syntax or a language to find elements on webpage using XML path expression

In the HTML, code is called ==> Tagname
In Xpath, code is called ==> Nodes

To navigate through each and every node to locate web element

At backend the HTML will load code however, browser acts as an intermediary layer

Dom view is navigated by browser and displayed as nodes
DOM is an API generated by browser when a webpage is loaded and where an expert works

XPath is mostly used for projects

TYPES OF XPATH
---------------
1. Absolute Xpath or Full Xpath e.g
    /Users/olakoya/PycharmProjects/Selenium
    /html/body/div/div/div/div/div/div/div/div/img (html locator for facebook logo)
    /parent element/child element/ grandchild element/

2. Relative Xpath or Short Xpath e.g
    ../PycharmProjects
    //tagname[@attribute='value']
    //img[@alt='Facebook'] (html locator for facebook logo)
    //tagname[@attribute='value']
    //tagname[@attribute=value] ==>
    //*[@attribute=value] e.g
Email ==> //*[@type='text']

If a developer introduces a new element or changes the location or path of an element then the absolute xpath will be broken.
So, Absolute XPATH is unstable and Relative XPATH is preferred

//*[@id="pass"] for email text box

We use driver.find_element(By.Tagname,"Input) to locate an element in the web page html
E.g
'''

from selenium import webdriver
from selenium.webdriver.common.by import By # 'by' is a module and inside it we have a class 'By'
opt = webdriver.ChromeOptions()
opt.add_experimental_option("detach" , True)

driver = webdriver.Chrome(options=opt)
driver.get("https://demowebshop.tricentis.com/")
driver.maximize_window()

# Absolute XPath
# driver.find_element((By.XPATH, "/html/body/div[4]/div[1]/div[1]/div[3]/form/input[1]")).send_keys("T-shirts")

# Relative XPath
# driver.find_element(By.XPATH, "//*[@id='small-searchterms']").send_keys("T-shirts")

driver.find_element(By.XPATH, "//input[@id='small-searchterms' and @value='Search store']").send_keys("Cars")

'''
XPath with and XPath with Operator

True and True ==> True
True or False ==> True

//input[@id="small-searchterms" and @value="Search store" or //input[@id='small-searchterms' and @value='Search store'

text()
------

Link Text or Visible Text ==> Inner Text

Multiple ways to locate link text and inner text

//tagname[text()="Register"]

//tagname[contains(text(),"regi"]

//tagname[contains(text(),"ster"]

//tagname[starts-with(text(),"Log"]
'''